/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.rdp.ms_books_catalogue.openapi;

import com.rdp.ms_books_catalogue.openapi.invoker.ApiException;
import java.math.BigDecimal;
import com.rdp.ms_books_catalogue.openapi.model.Book;
import com.rdp.ms_books_catalogue.openapi.model.BookDto;
import java.time.LocalDate;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BooksControllerApi
 */
class BooksControllerApiTest {

    private final BooksControllerApi api = new BooksControllerApi();

    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void createBookTest() throws ApiException {
        //
        //BookDto bookDto = null;
        //
        //Book response = api.createBook(bookDto);

        // TODO: test validations
    }
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void deleteBookTest() throws ApiException {
        //
        //Long id = null;
        //
        //String response = api.deleteBook(id);

        // TODO: test validations
    }
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getBookTest() throws ApiException {
        //
        //String id = null;
        //
        //Book response = api.getBook(id);

        // TODO: test validations
    }
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getBooksTest() throws ApiException {
        //
        //String title = null;
        //
        //String author = null;
        //
        //String category = null;
        //
        //String isbn = null;
        //
        //LocalDate publicationDate = null;
        //
        //Integer rating = null;
        //
        //BigDecimal price = null;
        //
        //String description = null;
        //
        //Boolean visible = null;
        //
        //List<Book> response = api.getBooks(title, author, category, isbn, publicationDate, rating, price, description, visible);

        // TODO: test validations
    }
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void patchBookTest() throws ApiException {
        //
        //Long id = null;
        //
        //Map<String, Object> requestBody = null;
        //
        //Book response = api.patchBook(id, requestBody);

        // TODO: test validations
    }
    /**
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void updateBookTest() throws ApiException {
        //
        //Long id = null;
        //
        //BookDto bookDto = null;
        //
        //Book response = api.updateBook(id, bookDto);

        // TODO: test validations
    }
}
