/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.rdp.ms_books_catalogue.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.LocalDate;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BookDto
 */
class BookDtoTest {
    private final BookDto model = new BookDto();

    /**
     * Model tests for BookDto
     */
    @Test
    void testBookDto() {
        // TODO: test BookDto
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'author'
     */
    @Test
    void authorTest() {
        // TODO: test author
    }

    /**
     * Test the property 'category'
     */
    @Test
    void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'isbn'
     */
    @Test
    void isbnTest() {
        // TODO: test isbn
    }

    /**
     * Test the property 'publicationDate'
     */
    @Test
    void publicationDateTest() {
        // TODO: test publicationDate
    }

    /**
     * Test the property 'rating'
     */
    @Test
    void ratingTest() {
        // TODO: test rating
    }

    /**
     * Test the property 'price'
     */
    @Test
    void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'visible'
     */
    @Test
    void visibleTest() {
        // TODO: test visible
    }

}
