# gateway.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-gateway
  namespace: relatos-de-papel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-gateway
  template:
    metadata:
      labels:
        app: ms-gateway
    spec:
      containers:
        - name: gateway
          image: gateway:latest # Cambiar por tu imagen
          imagePullPolicy: Never
          ports:
            - containerPort: 8762
          env:
            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: EUREKA_URL
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8762
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8762
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: ms-gateway
  namespace: relatos-de-papel
spec:
  selector:
    app: ms-gateway
  ports:
    - port: 8762
      targetPort: 8762
  type: LoadBalancer # Para acceso externo
